// Curated list of common emojis with their canonical shortcode names
// (matching GitHub / Slack / Discord conventions where possible) and a
// few keyword aliases. ~250 entries — enough for daily use without
// inflating the bundle. We intentionally don't ship the full Unicode
// emoji catalog; users who want every flag and skin tone modifier are
// better served by the OS picker.
//
// Format: [emoji, shortcode, ...keywords]

export const EMOJIS = [
    // Smileys
    ['😀', 'grinning', 'smile', 'happy'],
    ['😃', 'smiley', 'happy', 'smile'],
    ['😄', 'smile', 'happy'],
    ['😁', 'grin', 'happy'],
    ['😆', 'laughing', 'lol'],
    ['🤣', 'rofl', 'laughing'],
    ['😂', 'joy', 'tears', 'crying-laughing'],
    ['🙂', 'slightly-smiling', 'slight-smile'],
    ['🙃', 'upside-down'],
    ['😉', 'wink'],
    ['😊', 'blush', 'smile'],
    ['😇', 'innocent', 'angel'],
    ['🥰', 'smiling-with-hearts', 'love'],
    ['😍', 'heart-eyes', 'love'],
    ['🤩', 'star-struck', 'wow'],
    ['😘', 'kissing-heart', 'kiss'],
    ['😗', 'kissing'],
    ['😙', 'kissing-smiling-eyes'],
    ['😚', 'kissing-closed-eyes'],
    ['😋', 'yum', 'tasty'],
    ['😛', 'tongue', 'stuck-out-tongue'],
    ['😝', 'tongue-closed-eyes'],
    ['😜', 'tongue-wink', 'crazy'],
    ['🤪', 'zany', 'crazy'],
    ['🤨', 'raised-eyebrow', 'skeptical'],
    ['🧐', 'monocle', 'curious'],
    ['🤓', 'nerd', 'geek'],
    ['😎', 'sunglasses', 'cool'],
    ['🥸', 'disguise'],
    ['🤩', 'starstruck'],
    ['🥳', 'partying', 'party'],
    ['😏', 'smirk', 'smug'],
    ['😒', 'unamused'],
    ['😞', 'disappointed'],
    ['😔', 'pensive', 'sad'],
    ['😟', 'worried'],
    ['😕', 'confused'],
    ['🙁', 'slightly-frowning'],
    ['☹️', 'frowning', 'sad'],
    ['😣', 'persevering', 'struggle'],
    ['😖', 'confounded'],
    ['😫', 'tired-face'],
    ['😩', 'weary'],
    ['🥺', 'pleading', 'sad-puppy-eyes'],
    ['😢', 'cry', 'sad'],
    ['😭', 'sob', 'crying-loudly'],
    ['😤', 'huff', 'angry-steam'],
    ['😠', 'angry'],
    ['😡', 'rage', 'mad'],
    ['🤬', 'cursing', 'censored'],
    ['🤯', 'mind-blown', 'exploding-head'],
    ['😳', 'flushed'],
    ['🥵', 'hot', 'sweating'],
    ['🥶', 'cold', 'freezing'],
    ['😱', 'scream', 'shocked'],
    ['😨', 'fearful'],
    ['😰', 'anxious', 'cold-sweat'],
    ['😥', 'sad-but-relieved'],
    ['😓', 'sweat'],
    ['🤗', 'hug', 'hugging'],
    ['🤔', 'thinking', 'hmm'],
    ['🤭', 'shushing-hand', 'oops'],
    ['🤫', 'shushing', 'quiet'],
    ['🤥', 'lying', 'pinocchio'],
    ['😶', 'no-mouth'],
    ['😐', 'neutral'],
    ['😑', 'expressionless'],
    ['😬', 'grimacing', 'awkward'],
    ['🙄', 'eye-roll', 'rolling-eyes'],
    ['😯', 'hushed', 'surprised'],
    ['😦', 'frowning-open-mouth'],
    ['😧', 'anguished'],
    ['😮', 'open-mouth', 'wow'],
    ['😲', 'astonished'],
    ['🥱', 'yawn', 'tired'],
    ['😴', 'sleeping', 'asleep'],
    ['🤤', 'drooling'],
    ['😪', 'sleepy'],
    ['😵', 'dizzy'],
    ['🤐', 'zipper-mouth'],
    ['🥴', 'woozy'],
    ['🤢', 'nauseated'],
    ['🤮', 'vomiting'],
    ['🤧', 'sneezing'],
    ['😷', 'mask', 'sick'],
    ['🤒', 'thermometer', 'fever'],
    ['🤕', 'head-bandage', 'hurt'],
    ['🤑', 'money-mouth', 'rich'],
    ['🤠', 'cowboy'],
    ['😈', 'smiling-imp', 'devil'],
    ['👿', 'imp', 'devil-angry'],
    ['👹', 'ogre'],
    ['👺', 'goblin'],
    ['🤡', 'clown'],
    ['💩', 'poop', 'pile-of-poo'],
    ['👻', 'ghost'],
    ['💀', 'skull'],
    ['☠️', 'skull-and-crossbones'],
    ['👽', 'alien'],
    ['🤖', 'robot'],
    ['🎃', 'jack-o-lantern', 'pumpkin'],

    // Gestures + body
    ['👍', 'thumbsup', 'plus1', 'yes'],
    ['👎', 'thumbsdown', '-1', 'no'],
    ['👌', 'ok-hand'],
    ['🤌', 'pinched-fingers', 'italian'],
    ['🤏', 'pinching-hand', 'small'],
    ['✌️', 'peace', 'victory'],
    ['🤞', 'fingers-crossed', 'crossed-fingers'],
    ['🤟', 'love-you-gesture'],
    ['🤘', 'rock-on', 'horns'],
    ['🤙', 'call-me'],
    ['👈', 'point-left'],
    ['👉', 'point-right'],
    ['👆', 'point-up-2'],
    ['🖕', 'middle-finger'],
    ['👇', 'point-down'],
    ['☝️', 'point-up'],
    ['👋', 'wave'],
    ['🤚', 'raised-back-of-hand'],
    ['🖐️', 'raised-hand-with-fingers'],
    ['✋', 'raised-hand', 'high-five', 'stop'],
    ['🖖', 'vulcan'],
    ['👏', 'clap'],
    ['🙌', 'raised-hands', 'praise'],
    ['🤲', 'palms-up'],
    ['🤝', 'handshake'],
    ['🙏', 'pray', 'thank-you', 'thanks'],
    ['💪', 'muscle', 'strong', 'flex'],
    ['🫶', 'heart-hands'],
    ['👀', 'eyes', 'looking'],
    ['👁️', 'eye'],
    ['👅', 'tongue-out'],
    ['👄', 'mouth'],
    ['🦷', 'tooth'],
    ['🦴', 'bone'],
    ['🧠', 'brain'],
    ['❤️', 'heart', 'love', 'red-heart'],
    ['🧡', 'orange-heart'],
    ['💛', 'yellow-heart'],
    ['💚', 'green-heart'],
    ['💙', 'blue-heart'],
    ['💜', 'purple-heart'],
    ['🖤', 'black-heart'],
    ['🤍', 'white-heart'],
    ['🤎', 'brown-heart'],
    ['💔', 'broken-heart'],
    ['❣️', 'heart-exclamation'],
    ['💕', 'two-hearts'],
    ['💞', 'revolving-hearts'],
    ['💓', 'heartbeat'],
    ['💗', 'growing-heart'],
    ['💖', 'sparkling-heart'],
    ['💘', 'heart-with-arrow', 'cupid'],
    ['💝', 'heart-with-ribbon', 'gift'],
    ['💟', 'heart-decoration'],

    // Animals
    ['🐶', 'dog'],
    ['🐱', 'cat'],
    ['🐭', 'mouse'],
    ['🐹', 'hamster'],
    ['🐰', 'rabbit'],
    ['🦊', 'fox'],
    ['🐻', 'bear'],
    ['🐼', 'panda'],
    ['🐨', 'koala'],
    ['🐯', 'tiger'],
    ['🦁', 'lion'],
    ['🐷', 'pig'],
    ['🐸', 'frog'],
    ['🐵', 'monkey-face'],
    ['🐔', 'chicken'],
    ['🐧', 'penguin'],
    ['🦄', 'unicorn'],
    ['🐝', 'bee'],
    ['🐛', 'bug'],
    ['🦋', 'butterfly'],
    ['🐌', 'snail'],
    ['🐞', 'lady-beetle', 'ladybug'],
    ['🦀', 'crab'],
    ['🐠', 'tropical-fish'],
    ['🐟', 'fish'],
    ['🐬', 'dolphin'],
    ['🐳', 'whale'],
    ['🦈', 'shark'],
    ['🐢', 'turtle'],
    ['🐍', 'snake'],
    ['🦖', 'trex', 'dinosaur'],

    // Food + drink
    ['🍎', 'apple', 'red-apple'],
    ['🍐', 'pear'],
    ['🍊', 'orange'],
    ['🍋', 'lemon'],
    ['🍌', 'banana'],
    ['🍉', 'watermelon'],
    ['🍇', 'grapes'],
    ['🍓', 'strawberry'],
    ['🫐', 'blueberries'],
    ['🍒', 'cherries'],
    ['🍑', 'peach'],
    ['🥭', 'mango'],
    ['🍍', 'pineapple'],
    ['🥝', 'kiwi'],
    ['🍅', 'tomato'],
    ['🍆', 'eggplant'],
    ['🥑', 'avocado'],
    ['🌶️', 'hot-pepper', 'chili'],
    ['🌽', 'corn'],
    ['🥕', 'carrot'],
    ['🍞', 'bread'],
    ['🥐', 'croissant'],
    ['🥯', 'bagel'],
    ['🧀', 'cheese'],
    ['🥚', 'egg'],
    ['🍳', 'fried-egg'],
    ['🥞', 'pancakes'],
    ['🥓', 'bacon'],
    ['🍔', 'hamburger', 'burger'],
    ['🍟', 'fries'],
    ['🍕', 'pizza'],
    ['🌭', 'hotdog'],
    ['🥪', 'sandwich'],
    ['🌮', 'taco'],
    ['🌯', 'burrito'],
    ['🥗', 'salad'],
    ['🍿', 'popcorn'],
    ['🧂', 'salt'],
    ['🍦', 'soft-ice-cream', 'icecream'],
    ['🍩', 'doughnut', 'donut'],
    ['🍪', 'cookie'],
    ['🎂', 'birthday-cake', 'cake'],
    ['🍰', 'shortcake'],
    ['🍫', 'chocolate'],
    ['🍬', 'candy'],
    ['🍭', 'lollipop'],
    ['🍯', 'honey'],
    ['☕', 'coffee'],
    ['🍵', 'tea'],
    ['🧃', 'juice-box'],
    ['🥤', 'cup-with-straw'],
    ['🍺', 'beer'],
    ['🍻', 'beers', 'cheers'],
    ['🥂', 'champagne-glasses', 'toast'],
    ['🍷', 'wine-glass'],
    ['🥃', 'tumbler-glass', 'whiskey'],
    ['🍸', 'cocktail'],
    ['🍹', 'tropical-drink'],

    // Travel + places
    ['✈️', 'airplane'],
    ['🚀', 'rocket'],
    ['🛸', 'ufo'],
    ['🚗', 'car'],
    ['🚕', 'taxi'],
    ['🚙', 'suv'],
    ['🚌', 'bus'],
    ['🚓', 'police-car'],
    ['🚑', 'ambulance'],
    ['🚒', 'fire-truck'],
    ['🚲', 'bicycle'],
    ['🛴', 'kick-scooter'],
    ['🛵', 'motor-scooter'],
    ['🏍️', 'motorcycle'],
    ['🚂', 'train'],
    ['⛵', 'sailboat'],
    ['🚤', 'speedboat'],
    ['🚁', 'helicopter'],
    ['🌍', 'earth-globe', 'world'],
    ['🌎', 'earth-americas'],
    ['🌏', 'earth-asia'],
    ['🏠', 'house', 'home'],
    ['🏢', 'office'],
    ['🏥', 'hospital'],
    ['🏫', 'school'],
    ['⛺', 'tent'],
    ['🏖️', 'beach'],
    ['⛰️', 'mountain'],
    ['🌋', 'volcano'],
    ['🗻', 'fuji'],

    // Activities
    ['⚽', 'soccer'],
    ['🏀', 'basketball'],
    ['🏈', 'football'],
    ['⚾', 'baseball'],
    ['🎾', 'tennis'],
    ['🏐', 'volleyball'],
    ['🏉', 'rugby'],
    ['🎱', '8ball'],
    ['🎳', 'bowling'],
    ['🏓', 'ping-pong'],
    ['🏸', 'badminton'],
    ['🏒', 'hockey'],
    ['⛳', 'golf'],
    ['🎯', 'dart', 'target'],
    ['🎮', 'video-game'],
    ['🕹️', 'joystick'],
    ['🎲', 'dice'],
    ['🎼', 'musical-score'],
    ['🎵', 'music-note'],
    ['🎶', 'notes'],
    ['🎤', 'microphone'],
    ['🎧', 'headphones'],
    ['🎷', 'saxophone'],
    ['🎸', 'guitar'],
    ['🎹', 'keyboard-instrument'],
    ['🥁', 'drum'],
    ['🎬', 'clapper'],
    ['📷', 'camera'],
    ['📹', 'video-camera'],
    ['🎨', 'art', 'palette'],

    // Objects
    ['💻', 'computer', 'laptop'],
    ['🖥️', 'desktop'],
    ['⌨️', 'keyboard'],
    ['🖱️', 'mouse-three-button'],
    ['💾', 'floppy-disk', 'save'],
    ['💿', 'cd'],
    ['📱', 'phone', 'iphone'],
    ['☎️', 'telephone'],
    ['📞', 'telephone-receiver'],
    ['🔌', 'plug'],
    ['🔋', 'battery'],
    ['🛜', 'wifi'],
    ['📡', 'satellite', 'antenna'],
    ['🔍', 'magnifying-glass', 'search'],
    ['🔎', 'magnifying-glass-right'],
    ['💡', 'bulb', 'idea', 'light'],
    ['🔦', 'flashlight'],
    ['🕯️', 'candle'],
    ['🧯', 'fire-extinguisher'],
    ['🪛', 'screwdriver'],
    ['🔧', 'wrench'],
    ['🔨', 'hammer'],
    ['🪓', 'axe'],
    ['📌', 'pushpin'],
    ['📎', 'paperclip'],
    ['📒', 'notebook'],
    ['📚', 'books'],
    ['🗒️', 'notepad'],
    ['📋', 'clipboard'],
    ['📁', 'folder'],
    ['📂', 'open-folder'],
    ['🗂️', 'card-index-dividers'],
    ['📅', 'calendar'],
    ['📆', 'tear-off-calendar'],
    ['📊', 'bar-chart'],
    ['📈', 'chart-up'],
    ['📉', 'chart-down'],
    ['💵', 'dollar'],
    ['💰', 'money-bag'],
    ['💳', 'credit-card'],
    ['🧾', 'receipt'],
    ['💸', 'flying-money'],
    ['🛒', 'shopping-cart'],
    ['🎁', 'gift', 'present'],
    ['🎈', 'balloon'],
    ['🎉', 'tada', 'party'],
    ['🎊', 'confetti'],
    ['🎀', 'ribbon'],

    // Symbols
    ['❤️', 'red-heart'],
    ['💯', '100', 'hundred'],
    ['💢', 'anger'],
    ['💥', 'boom', 'collision'],
    ['💫', 'dizzy-symbol'],
    ['💦', 'sweat-droplets'],
    ['💨', 'dash'],
    ['🕳️', 'hole'],
    ['💣', 'bomb'],
    ['💬', 'speech-balloon'],
    ['🗨️', 'left-speech-bubble'],
    ['💭', 'thought-balloon'],
    ['🛑', 'stop-sign'],
    ['⚠️', 'warning'],
    ['🚸', 'children-crossing'],
    ['🔞', 'no-one-under-18'],
    ['❓', 'question'],
    ['❔', 'white-question'],
    ['❗', 'exclamation', 'bang'],
    ['❕', 'white-exclamation'],
    ['‼️', 'double-exclamation'],
    ['⁉️', 'interrobang'],
    ['✅', 'check', 'white-check', 'checkmark'],
    ['☑️', 'ballot-check'],
    ['✔️', 'heavy-check'],
    ['❌', 'x', 'cross', 'no'],
    ['❎', 'negative-cross'],
    ['➕', 'plus'],
    ['➖', 'minus'],
    ['➗', 'divide'],
    ['✖️', 'multiply'],
    ['💲', 'heavy-dollar'],
    ['🔥', 'fire', 'lit'],
    ['⭐', 'star'],
    ['🌟', 'glowing-star'],
    ['✨', 'sparkles'],
    ['⚡', 'zap', 'lightning'],
    ['☄️', 'comet'],
    ['🌈', 'rainbow'],
    ['☀️', 'sunny', 'sun'],
    ['🌙', 'moon'],
    ['⛅', 'partly-cloudy'],
    ['☁️', 'cloud'],
    ['🌧️', 'cloud-rain'],
    ['❄️', 'snowflake'],
    ['🌊', 'wave'],
    ['💧', 'droplet'],
    ['🔒', 'lock'],
    ['🔓', 'unlock'],
    ['🔑', 'key'],
    ['🚫', 'no-entry-sign', 'forbidden'],
    ['⏰', 'alarm-clock'],
    ['⏱️', 'stopwatch'],
    ['⏲️', 'timer'],
    ['🕰️', 'mantelpiece-clock'],

    // Time / arrows
    ['◀️', 'left-arrow'],
    ['▶️', 'right-arrow'],
    ['🔼', 'up-arrow-button'],
    ['🔽', 'down-arrow-button'],
    ['⬆️', 'up-arrow'],
    ['⬇️', 'down-arrow'],
    ['⬅️', 'leftwards-arrow'],
    ['➡️', 'rightwards-arrow'],
    ['↗️', 'up-right'],
    ['↘️', 'down-right'],
    ['↙️', 'down-left'],
    ['↖️', 'up-left'],
    ['🔃', 'arrows-clockwise'],
    ['🔄', 'arrows-counterclockwise'],
    ['🔁', 'repeat'],
    ['🔂', 'repeat-one'],
    ['🔀', 'shuffle'],

    // Misc
    ['🚀', 'rocket'],
    ['💎', 'gem', 'diamond'],
    ['🪐', 'planet'],
    ['🌐', 'globe'],
    ['🆕', 'new'],
    ['🆗', 'ok-square'],
    ['🆙', 'up'],
    ['🆒', 'cool-square'],
    ['🆓', 'free'],
    ['🆘', 'sos'],
    ['🆔', 'id'],
    ['🚨', 'rotating-light', 'siren'],
    ['🛡️', 'shield'],
    ['🪄', 'magic-wand'],
];
