// Short EFF-inspired wordlist (~256 entries, common 4-7 letter words).
// Smaller than the full EFF list but still gives ~8 bits per word, so a
// 4-word passphrase has ~32 bits of entropy.

export const WORDS = [
    'amber', 'anchor', 'apple', 'arcade', 'arctic', 'armor', 'arrow', 'aspen',
    'atlas', 'autumn', 'badge', 'banana', 'banjo', 'basil', 'beach', 'beaver',
    'belt', 'berry', 'biscuit', 'bison', 'blade', 'blanket', 'blaze', 'blink',
    'blossom', 'blue', 'boat', 'bonus', 'book', 'boost', 'border', 'bottle',
    'bounce', 'bowl', 'box', 'brain', 'branch', 'brave', 'bread', 'breeze',
    'bridge', 'bright', 'brisk', 'brook', 'broom', 'brown', 'brush', 'bubble',
    'buddy', 'buffalo', 'bunny', 'cactus', 'calm', 'camel', 'candle', 'canoe',
    'canyon', 'cargo', 'carpet', 'carrot', 'castle', 'cedar', 'cement', 'chair',
    'chalk', 'cherry', 'chess', 'chime', 'cinnamon', 'circle', 'clay', 'cliff',
    'cloud', 'clover', 'cobalt', 'cocoa', 'coffee', 'comet', 'cookie', 'coral',
    'cosmic', 'cottage', 'cotton', 'cougar', 'crayon', 'crisp', 'crow', 'crown',
    'crystal', 'cyclone', 'daisy', 'dapper', 'daring', 'darkly', 'dawn', 'deer',
    'delta', 'denim', 'desert', 'diamond', 'dimple', 'dingo', 'disco', 'dolphin',
    'donut', 'doodle', 'dove', 'dragon', 'drift', 'drum', 'dusk', 'eagle',
    'earth', 'ebony', 'echo', 'eclipse', 'elf', 'elm', 'ember', 'engine',
    'epic', 'estate', 'ethic', 'ever', 'fable', 'falcon', 'fancy', 'feather',
    'felt', 'fern', 'fest', 'fiber', 'field', 'fierce', 'fig', 'finch',
    'fjord', 'flag', 'flame', 'fleet', 'flint', 'flora', 'flute', 'foggy',
    'forest', 'forge', 'fortune', 'fossil', 'fox', 'frog', 'frost', 'galaxy',
    'gallop', 'garden', 'garnet', 'gather', 'gear', 'gem', 'gentle', 'ghost',
    'giant', 'gift', 'ginger', 'glide', 'globe', 'gloss', 'glow', 'goal',
    'goblin', 'golden', 'gondola', 'gorilla', 'grace', 'grain', 'grand', 'grape',
    'grass', 'gray', 'great', 'green', 'grin', 'grove', 'gulp', 'guppy',
    'gusty', 'happy', 'harbor', 'harvest', 'hawk', 'hazel', 'heron', 'hill',
    'hippo', 'hive', 'honey', 'hoop', 'horn', 'hummer', 'husky', 'icicle',
    'iguana', 'indigo', 'inland', 'iris', 'iron', 'island', 'ivory', 'ivy',
    'jaguar', 'jazz', 'jelly', 'jovial', 'juicy', 'jumpy', 'juniper', 'kayak',
    'kelp', 'kernel', 'kiwi', 'koala', 'lagoon', 'lake', 'lamp', 'lantern',
    'larch', 'laser', 'leaf', 'lemon', 'leopard', 'lever', 'library', 'lilac',
    'lime', 'linen', 'lion', 'liquid', 'lively', 'lobby', 'lobster', 'locket',
    'lodge', 'lofty', 'logic', 'lotus', 'lucky', 'lunar', 'magnet', 'magnolia',
    'mango', 'maple', 'marble', 'marsh', 'meadow', 'medic', 'melon', 'meteor',
    'mighty', 'milky', 'mimosa', 'minty', 'mirror', 'misty', 'molar', 'moose',
    'morning', 'mosaic', 'moth', 'motor', 'mountain', 'movie', 'muffin',
];
